data_ingestion:
  bucket_name: "hotel_reservation_23456"
  bucket_file_name: "Hotel_Reservations.csv"
  train_ratio: 0.8

data_processing:
  categorical_columns:
    - type_of_meal_plan
    - required_car_parking_space 
    - room_type_reserved 
    - market_segment_type
    - repeated_guest 
    - booking_status

  numerical_columns:
    - arrival_date
    - no_of_special_requests
    - arrival_month
    - no_of_weekend_nights
    - no_of_previous_cancellations
    - arrival_year
    - no_of_children
    - no_of_week_nights
    - lead_time
    - no_of_adults
    - no_of_previous_bookings_not_canceled
    - avg_price_per_room
  
  skewness_threshold: 5
  num_features_to_select: 10